services:
    web:
        build: .
        command: bash -c 'poetry install --sync && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000'
        volumes:
            - .:/app
        ports:
            - 18000:8000
