services:
    web:
        user: "${UID}:${GID}"
        container_name: "htmx-fastapi"
        command: "bash -c 'uv run --dev uvicorn src.main:app --host 0.0.0.0 --reload --port 8000'"
        build:
            context: ..
            dockerfile: docker/dockerfile
            args:
                - UID=${UID}
                - GID=${GID}
        env_file:
            - docker.env
        develop:
            watch:
                # https://docs.docker.com/compose/how-tos/file-watch/#sync--restart
                - action: sync+restart
                  path: ../
                  target: /app/
        ports:
            - "${SERVER_PORT}:8000"
