# https://hub.docker.com/_/python/tags
FROM docker.io/python:3.13-slim

# create user
ENV USER_ID=1000
ENV GROUP_ID=1000
ENV HOME=/home/appuser
ENV PATH="$HOME/.local/bin:$PATH"
ENV PYTHONUNBUFFERED=1
RUN groupadd -g $GROUP_ID appuser && \
    useradd -u $USER_ID -g appuser -m appuser && \
    mkdir -p $HOME/.cache && \
    chown -R appuser:appuser $HOME && \
    mkdir -p /app && \
    chown -R appuser:appuser /app
USER appuser

WORKDIR /app

# copy only project dependencies for caching
COPY uv.lock pyproject.toml /app/

# install uv after dependencies to grab latest when updating
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_LINK_MODE="copy"
ENV UV_CACHE_DIR="$HOME/.cache/uv/"

RUN uv sync --locked
ADD . /app

EXPOSE 8000
